// File generated by FlutterFire CLI.
// Contains default Firebase configuration for your app
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration - you'll need to update this with your web project values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgx4b15Af70U4jsatbxZ72vDanKCPa6M',
    appId: '1:646814822252:web:7b1b9ba2c3fda56f2a0d49', // This is a placeholder, update with actual web appId
    messagingSenderId: '646814822252',
    projectId: 'flyingautoservices-e0225',
    authDomain: 'flyingautoservices-e0225.firebaseapp.com',
    storageBucket: 'flyingautoservices-e0225.firebasestorage.app',
  );

  // Android configuration - you'll need to update this with your Android project values
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgx4b15Af70U4jsatbxZ72vDanKCPa6M',
    appId: '1:646814822252:android:7b1b9ba2c3fda56f2a0d49', // This is a placeholder, update with actual Android appId
    messagingSenderId: '646814822252',
    projectId: 'flyingautoservices-e0225',
    storageBucket: 'flyingautoservices-e0225.firebasestorage.app',
  );

  // iOS configuration from GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvgx4b15Af70U4jsatbxZ72vDanKCPa6M',
    appId: '1:646814822252:ios:7b1b9ba2c3fda56f2a0d49',
    messagingSenderId: '646814822252',
    projectId: 'flyingautoservices-e0225',
    storageBucket: 'flyingautoservices-e0225.firebasestorage.app',
    iosBundleId: 'com.flyingautoservices.flyingAutoServices',
  );

  // macOS configuration - you'll need to update this with your macOS project values
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvgx4b15Af70U4jsatbxZ72vDanKCPa6M',
    appId: '1:646814822252:ios:7b1b9ba2c3fda56f2a0d49', // This is a placeholder, update with actual macOS appId
    messagingSenderId: '646814822252',
    projectId: 'flyingautoservices-e0225',
    storageBucket: 'flyingautoservices-e0225.firebasestorage.app',
    iosBundleId: 'com.flyingautoservices.flyingAutoServices',
  );
}
